Fixed TypeError when loading remind from brain
When hubot were restarted, loading reminders from brain caused:
TypeError: Object fooobar memory has no method 'getTime'

Fixed missing constructor parameter.